repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: poetry run isort
        types: [python]

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: poetry run black
        types: [python]

      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: poetry run flake8
        types: [python]

      - id: pyright
        name: pyright
        stages: [commit]
        language: system
        entry: poetry run pyright
        types: [python]

      - id: pytest
        name: pytest
        stages: [commit]
        language: system
        entry: poetry run pytest --cov
        types: [python]
        always_run: true
        pass_filenames: false
